# Generated by Django 3.2.19 on 2023-05-14 22:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(400)])),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=200)),
                ('work_title', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, default='default_profile_image.png', null=True, upload_to=profiles.models.upload_to)),
                ('booked_workshifts', models.ManyToManyField(related_name='booked_by', to='scheduling.WorkShift')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
